import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppLayoutProvider } from "@/context/AppLayoutContext";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import { DataProvider } from "@/context/DataContext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <Suspense fallback={<div>Loading...</div>}>
          <DataProvider>
            <AppLayoutProvider>
              <Header />
              <section className='flex flex-row'>
                <SideBar
                  items={["Dashboard", "Transactions", "Reports", "Settings"]}
                />
                <div className='flex-[1_1_auto] pt-4 px-12'>{children}</div>
              </section>
            </AppLayoutProvider>
          </DataProvider>
        </Suspense>
      </body>
    </html>
  );
}

